[package]
org = "wso2"
name = "sfdc_sa_service"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
artifactId = "mysql-connector-java"
version = "8.0.23"
path = "/Users/Shared/Software/mysql-connector-java-8.0.23.jar"
groupId = "mysql"